version: "3.8"

services:
  postgres-service:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_DB:learn
      - POSTGRES_PASSWORD:password
  redis-service:
    image: redis
    ports:
      - "6379:6379"
